os: Visual Studio 2015

# version format
version: 1.5.4.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

build_script:
- build-appveyor.cmd

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
     # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-vorto/
    symbol_server: https://nuget.symbolsource.org/MyGet/umbraco-vorto
    api_key:
      secure: gHDTL46KZcLzj6J8m//TJgaCOJCl9ixR//rXjO18HRlCsfPYYz7dU81u2D5zd+ZN
    artifact: /.*\.nupkg/
    on:
      branch: develop

     # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: GyY9va9/RfmO6mK7xMhaciO9mtep3HYW0DEPeFVUBbYvZGRjk8enQ/tW6id6yE7D
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

     # NuGet Deployment for releases
  - provider: NuGet
    server: 
    api_key:
      secure: q2Aov00i+eWTpbwWHB1JN8EAGw4o8FaOC2lj2MolyS6TGkUUFTJK/vQTQzaf/EQ5
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
